CREATE TABLE IF NOT EXISTS LOGS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created TIMESTAMP
);

INSERT INTO LOGS(created) VALUES(CURRENT_TIMESTAMP - INTERVAL '10' DAY);
INSERT INTO LOGS(created) VALUES(CURRENT_TIMESTAMP - INTERVAL '9' DAY);
INSERT INTO LOGS(created) VALUES(CURRENT_TIMESTAMP - INTERVAL '8' DAY);
INSERT INTO LOGS(created) VALUES(CURRENT_TIMESTAMP - INTERVAL '7' DAY);
INSERT INTO LOGS(created) VALUES(CURRENT_TIMESTAMP - INTERVAL '6' DAY);